import React from 'react';
import ServiceLayout from '../../../../components/ServiceLayout';
import { Activity, ShieldCheck, Zap, Radio, Search, Wrench, FileCheck, Layers } from 'lucide-react';
import heroImage from "../../../../assets/imagesss/healthcare/EMIEMCforMedicalDevices.png";

const SEQUENCE_FEATURES = [
    { id: 1, title: "Architecture Review", desc: "Reviewing the schematic and PCB layout to identify ground loops, floating metal, and poor return paths." },
    { id: 2, title: "Pre-Compliance", desc: "Using near-field probes and benchtop spectrum analyzers to locate specific noisy components before hitting the chamber." },
    { id: 3, title: "Emissions Testing", desc: "Placing the device in an anechoic chamber to measure radiated emissions against CISPR 11 Class A or B limits." },
    { id: 4, title: "Immunity Testing", desc: "Subjecting the device to intense RF fields (up to 28 V/m) to ensure it doesn't malfunction near walkie-talkies or RFID readers." },
    { id: 5, title: "ESD Testing", desc: "Zapping the enclosure and IO ports with 8kV to 15kV static discharges (IEC 61000-4-2) to verify robustness." },
    { id: 6, title: "Mitigation", desc: "If a test fails, we rapidly apply surgical fixes (ferrites, copper tape, RC snubbers) to pass, then update the PCB layout." }
];

const COLLAGE_IMAGES = [
    { src: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=800", scaleIndex: 4, cls: "!-top-[30vh] !left-[5vw] !h-[30vh] !w-[35vw]" },
    { src: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800", scaleIndex: 5, cls: "!-top-[10vh] !-left-[25vw] !h-[45vh] !w-[20vw]" },
    { src: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=800", scaleIndex: 6, cls: "!left-[27.5vw] !h-[25vh] !w-[25vw]" },
    { src: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=800", scaleIndex: 5, cls: "!top-[27.5vh] !left-[5vw] !h-[25vh] !w-[20vw]" },
    { src: "https://images.unsplash.com/photo-1503376713197-285a4a4ebf32?q=80&w=800", scaleIndex: 6, cls: "!top-[27.5vh] !-left-[22.5vw] !h-[25vh] !w-[30vw]" },
    { src: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=800", scaleIndex: 8, cls: "!top-[22.5vh] !left-[25vw] !h-[15vh] !w-[15vw]" },
];

const SHOWCASE_FEATURES = [
    {
        id: "01",
        title: "CISPR 11 (Emissions)",
        description: "Ensuring your medical device does not pollute the hospital's electromagnetic environment, which could interfere with other critical equipment.",
        points: ["Radiated emissions", "Conducted emissions", "Class A (Hospital) / B (Home)"],
        image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop&q=80",
        color: "from-blue-500/20 to-purple-500/20"
    },
    {
        id: "02",
        title: "IEC 60601-1-2 (Immunity)",
        description: "Subjecting the device to massive electromagnetic interference to ensure it continues to operate safely in a chaotic hospital environment.",
        points: ["Radiated RF immunity", "Electrical Fast Transients (EFT)", "Magnetic fields"],
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80",
        color: "from-emerald-500/20 to-teal-500/20"
    },
    {
        id: "03",
        title: "IEC 61000-4-2 (ESD)",
        description: "Protecting sensitive silicon from 15,000-volt static shocks delivered by a doctor walking across a dry carpet.",
        points: ["Air discharge (15kV)", "Contact discharge (8kV)", "TVS Diode arrays"],
        image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&auto=format&fit=crop&q=80",
        color: "from-orange-500/20 to-red-500/20"
    },
    {
        id: "04",
        title: "Electrosurgery Protection",
        description: "Ensuring patient monitors and scopes survive the intense, high-frequency noise generated by surgical cutting tools (Bovies).",
        points: ["High-frequency noise", "Input filtering", "Analog blanking"],
        image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&auto=format&fit=crop&q=80",
        color: "from-pink-500/20 to-rose-500/20"
    }
];

const LATEST_INSIGHTS = [
  {
    id: 1,
    tag: "Regulation",
    title: "Understanding the Changes in IEC 60601-1-2 4th Edition",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop&q=80"
  },
  {
    id: 2,
    tag: "Design for EMC",
    title: "Stopping Emissions at the Source: PCB Grounding Strategies",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80"
  },
  {
    id: 3,
    tag: "ESD",
    title: "Proper TVS Diode Placement for 15kV Air Discharge Immunity",
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&auto=format&fit=crop&q=80"
  }
];

const EMC_SUB_SERVICES = [
    { title: "Design for EMC", description: "EMC is solved in the PCB layout, not by wrapping the box in foil. We review traces, planes, and decoupling to ensure quiet operation from day one.", icon: <Layers className="w-6 h-6 text-neutral-900" />, image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop&q=80" },
    { title: "Shielding & Enclosures", description: "Designing mechanical enclosures with conductive gaskets, EMI absorbing foam, and Faraday cages for noisy components like motors and displays.", icon: <ShieldCheck className="w-6 h-6 text-neutral-900" />, image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80" },
    { title: "Lab Pre-Compliance", description: "Test chamber time costs $2000/day. We run pre-compliance tests in our own labs to ensure you pass the real test on the first try.", icon: <Search className="w-6 h-6 text-neutral-900" />, image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&auto=format&fit=crop&q=80" },
    { title: "Failure Debugging", description: "If a board fails homologation, we fly to the test house. We don't just guess; we use physics to find the specific trace acting as an antenna.", icon: <Wrench className="w-6 h-6 text-neutral-900" />, image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&auto=format&fit=crop&q=80" },
    { title: "ESD Protection Design", description: "Placing Transient Voltage Suppressor (TVS) diodes directly at IO ports (USB, HDMI) to clamp massive 15kV static shocks to a safe level.", icon: <Zap className="w-6 h-6 text-neutral-900" />, image: "https://images.unsplash.com/photo-1503376713197-285a4a4ebf32?w=800&auto=format&fit=crop&q=80" },
    { title: "Test Plan Generation", description: "Writing the formal EMC Test Plan required by the FDA and the test laboratory, specifying exactly how the device must be exercised during the test.", icon: <FileCheck className="w-6 h-6 text-neutral-900" />, image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&auto=format&fit=crop&q=80" }
];

const EMC_ADVANTAGES = [
    { title: "First-Pass Success", description: "Failing EMC testing delays product launches by months. Our 'Design for EMC' methodology dramatically increases first-pass yield.", icon: <ShieldCheck className="w-6 h-6" /> },
    { title: "Root Cause Analysis", description: "When a failure occurs, we don't 'shotgun' capacitors onto the board. We find the exact parasitic inductance causing the resonance.", icon: <Search className="w-6 h-6" /> },
    { title: "Standards Experts", description: "The 4th Edition of IEC 60601-1-2 introduced massive changes (like testing immunity against RFID readers). We know the standards inside out.", icon: <FileCheck className="w-6 h-6" /> },
    { title: "Home Healthcare (Class B)", description: "Home-use medical devices (like CPAP machines) have much stricter emission limits than hospital devices. We know how to hit Class B limits.", icon: <Radio className="w-6 h-6" /> }
];

const EMC_FAQ = [
    {
        question: "What is the difference between Emissions and Immunity?",
        answer: "Emissions means your device is spitting out radio waves that could jam a nearby pacemaker or hospital Wi-Fi. Immunity means your device can survive being blasted by a walkie-talkie without crashing."
    },
    {
        question: "What changed in the 4th Edition of IEC 60601-1-2?",
        answer: "The 4th Edition drastically increased the immunity requirements. Medical devices must now survive much higher levels of static discharge (15kV) and must be proven to operate safely when placed right next to active RFID readers and LTE cell phones."
    },
    {
        question: "Can't we just paint the inside of the plastic enclosure with conductive paint?",
        answer: "You can, but it is expensive, flakes off, and if any wire passes through the paint, it acts as an antenna and broadcasts the noise anyway. It is always cheaper and more reliable to fix the noise at the source: the PCB layout."
    },
    {
        question: "What is an Electrical Fast Transient (EFT)?",
        answer: "When a large motor (like an elevator or a hospital HVAC unit) turns on or off, it creates a massive voltage spike on the hospital's power grid. We test medical devices to ensure they survive these spikes without rebooting or shocking the patient."
    }
];

const EMC_ABOUT_METRICS = {
    titlePart1: "About",
    titlePart2: "Medical EMC Compliance",
    description: "U&WE tames the electromagnetic chaos of the modern hospital. We engineer medical devices that remain 'whisper quiet' to surrounding equipment, while surviving massive static shocks and intense RF interference.",
    metrics: [
        { tag: "EMISSIONS", value: "CISPR 11", label: "Class A / B", image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=800&auto=format&fit=crop" },
        { tag: "IMMUNITY", value: "60601-1-2", label: "4th Edition Standards", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop" },
        { tag: "STATIC", value: "15kV", label: "ESD Air Discharge", image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=800&auto=format&fit=crop" },
        { tag: "DEBUG", value: "Near-Field", label: "Root Cause Isolation", image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=800&auto=format&fit=crop" }
    ]
};

const MedicalEmc = () => {
    return (
        <ServiceLayout 
            hero={{
                title: "EMI/EMC for Medical Devices",
                description: "Engineering 'Design for EMC' PCBs and mitigating radiated/conducted emissions to pass rigorous IEC 60601-1-2 (4th Edition) standards.",
                primaryButtonText: "Get Started",
                secondaryButtonText: "View Capabilities",
                image: heroImage
            }}
            aboutMetrics={EMC_ABOUT_METRICS}
            subServices={EMC_SUB_SERVICES}
            subServicesTitle={{ part1: "Core", part2: "Capabilities" }}
            advantages={EMC_ADVANTAGES}
            advantagesTitle={{ part1: "Why Partner", part2: "With Us" }}
            faqs={EMC_FAQ}
            portal={{
                portalImage: heroImage,
                gridImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2564&auto=format&fit=crop",
                collageImages: COLLAGE_IMAGES,
                features: SEQUENCE_FEATURES,
                aboutText: (
                    <p className="text-[clamp(1.1rem,2vw,2.2rem)] font-medium leading-[1.6] tracking-tight text-left text-neutral-900">
                        Mastering the invisible spectrum.
                        <br className="hidden lg:block mt-2" />
                        We ensure your device survives the real world.
                    </p>
                )
            }}
            slider={{
                title: "Latest in EMC",
                subtitle: "Insights from our compliance engineers",
                cards: LATEST_INSIGHTS
            }}
            showcase={{
                features: SHOWCASE_FEATURES,
                backgroundText: "COMPLIANCE"
            }}
        />
    );
};

export default MedicalEmc;
